name: "Release"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish_release:
    runs-on: ubuntu-latest
    name: Publish Release

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (required for semantic-release)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies for semantic-release
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/github @semantic-release/git

      # Step 4: Run semantic-release
      - name: Generate version and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release

      # Step 5: Setup Go (required for GoReleaser)
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      # Step 6: Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
