name: "Release"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  publish_release:
    runs-on: ubuntu-24.04
    name: Create release to Midaz
    steps:

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
